import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ru' | 'uk' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'ar' | 'pt' | 'it' | 'nl' | 'pl' | 'tr' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.forInvestors': 'For Investors',
    'nav.aboutUs': 'About Us',
    'nav.team': 'Team',
    'nav.contact': 'Contact',
    'nav.news': 'News & Insights',
    'nav.howItWorks': 'How It Works',
    'nav.investorInfo': 'Investor Information',
    'common.learnMore': 'Learn More',
    'common.viewDetails': 'View Details',
    'common.viewAll': 'View All',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.close': 'Close',
    'common.download': 'Download',
    'common.readMore': 'Read More',
    'hero.title': 'Building Real-Economy and Advanced Technology Projects',
    'hero.subtitle': 'Multi-sector portfolio across health, agriculture, food systems, and AI infrastructure',
    'hero.cta1': 'Explore Projects',
    'hero.cta2': 'Investment Information',
    'projects.title': 'Our Projects',
    'projects.subtitle': 'Explore our diverse portfolio of technology and real-economy ventures',
    'projects.featured': 'Featured Projects',
    'projects.viewAll': 'View All Projects',
    'projects.status.open': 'Open',
    'projects.status.closed': 'Closed',
    'projects.status.comingSoon': 'Coming Soon',
    'projects.submitInterest': 'Submit Interest',
    'projects.learnMore': 'Learn More',
    'projects.category': 'Category',
    'projects.location': 'Location',
    'form.name': 'Name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.country': 'Country',
    'form.message': 'Message',
    'form.comments': 'Comments',
    'form.interestLevel': 'Approximate interest level (optional, non-binding)',
    'form.required': 'Required',
    'form.optional': 'Optional',
    'form.submitRequest': 'Submit Information Request',
    'form.sending': 'Sending...',
    'form.success': 'Thank you! Your request has been received. We will contact you shortly.',
    'form.error': 'Something went wrong. Please try again.',
    'form.disclaimer': 'This is a non-binding expression of interest and does not constitute a commitment or offer.',
    'disclaimer.investment': 'Digital Invest Inc. is not an investment advisor, broker-dealer, crowdfunding platform, or public marketplace. Participation in any project is handled privately, offline, and only for eligible individuals or entities following due diligence.',
    'disclaimer.global': 'Digital Invest Inc. is a private entity. This website is for informational purposes only and does not constitute an offer to sell, a solicitation of an offer to buy, or a recommendation of any securities or financial instruments.',
    'disclaimer.noGuarantees': 'Nothing on this website should be construed as investment, legal, tax, or financial advice. No guarantees, promises, or forward-looking returns are made or implied.',
    'footer.company': 'Company',
    'footer.projects': 'Projects',
    'footer.legal': 'Legal & Risk',
    'footer.press': 'Press & Resources',
    'footer.contact': 'Contact',
    'footer.description': 'Building and scaling real-economy, AI, manufacturing, and health-technology projects across the United States.',
    'footer.copyright': '© 2025 Digital Invest Inc. All rights reserved.',
    'team.title': 'Our Team',
    'team.subtitle': 'Meet the professionals driving innovation and growth at Digital Invest Inc.',
    'team.founderTitle': 'Executive Leadership',
    'team.teamMembers': 'Team Members',
    'team.teamSubtitle': 'Experienced professionals across technology, operations, and strategic development',
    'glossary.title': 'Investment Glossary',
    'glossary.subtitle': 'Essential financial terms and abbreviations',
    'glossary.search': 'Search terms...',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.projects': 'Проекты',
    'nav.forInvestors': 'Для Инвесторов',
    'nav.aboutUs': 'О Нас',
    'nav.team': 'Команда',
    'nav.contact': 'Контакты',
    'nav.news': 'Новости и Статьи',
    'nav.howItWorks': 'Как Это Работает',
    'nav.investorInfo': 'Информация для Инвесторов',
    'common.learnMore': 'Узнать Больше',
    'common.viewDetails': 'Подробнее',
    'common.viewAll': 'Посмотреть Все',
    'common.submit': 'Отправить',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.back': 'Назад',
    'common.loading': 'Загрузка...',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.close': 'Закрыть',
    'common.download': 'Скачать',
    'common.readMore': 'Читать Далее',
    'hero.title': 'Создание Проектов Реальной Экономики и Передовых Технологий',
    'hero.subtitle': 'Мультисекторальный портфель в сферах здравоохранения, сельского хозяйства, пищевых систем и AI инфраструктуры',
    'hero.cta1': 'Изучить Проекты',
    'hero.cta2': 'Инвестиционная Информация',
    'projects.title': 'Наши Проекты',
    'projects.subtitle': 'Изучите наш разнообразный портфель технологических и реально-экономических проектов',
    'projects.featured': 'Избранные Проекты',
    'projects.viewAll': 'Посмотреть Все Проекты',
    'projects.status.open': 'Открыт',
    'projects.status.closed': 'Закрыт',
    'projects.status.comingSoon': 'Скоро',
    'projects.submitInterest': 'Выразить Интерес',
    'projects.learnMore': 'Узнать Больше',
    'projects.category': 'Категория',
    'projects.location': 'Местоположение',
    'form.name': 'Имя',
    'form.email': 'Электронная почта',
    'form.phone': 'Телефон',
    'form.country': 'Страна',
    'form.message': 'Сообщение',
    'form.comments': 'Комментарии',
    'form.interestLevel': 'Приблизительный уровень интереса (необязательно, необязывающий)',
    'form.required': 'Обязательно',
    'form.optional': 'Необязательно',
    'form.submitRequest': 'Отправить Запрос Информации',
    'form.sending': 'Отправка...',
    'form.success': 'Спасибо! Ваш запрос получен. Мы свяжемся с вами в ближайшее время.',
    'form.error': 'Что-то пошло не так. Пожалуйста, попробуйте снова.',
    'form.disclaimer': 'Это необязывающее выражение интереса и не является обязательством или предложением.',
    'disclaimer.investment': 'Digital Invest Inc. не является инвестиционным консультантом, брокером-дилером, краудфандинговой платформой или публичным рынком. Участие в любом проекте осуществляется в частном порядке, офлайн и только для соответствующих физических или юридических лиц после проверки.',
    'disclaimer.global': 'Digital Invest Inc. является частной компанией. Этот сайт предназначен только для информационных целей и не является предложением о продаже, приглашением к покупке или рекомендацией каких-либо ценных бумаг или финансовых инструментов.',
    'disclaimer.noGuarantees': 'Ничто на этом сайте не должно рассматриваться как инвестиционная, юридическая, налоговая или финансовая консультация. Никаких гарантий, обещаний или прогнозируемых доходов не предоставляется и не подразумевается.',
    'footer.company': 'Компания',
    'footer.projects': 'Проекты',
    'footer.legal': 'Юридические Вопросы',
    'footer.press': 'Пресса и Ресурсы',
    'footer.contact': 'Контакты',
    'footer.description': 'Создание и масштабирование проектов реальной экономики, ИИ, производства и здравоохранения по всем Соединенным Штатам.',
    'footer.copyright': '© 2025 Digital Invest Inc. Все права защищены.',
    'team.title': 'Наша Команда',
    'team.subtitle': 'Познакомьтесь с профессионалами, которые ведут инновации и рост в Digital Invest Inc.',
    'team.founderTitle': 'Исполнительное Руководство',
    'team.teamMembers': 'Члены Команды',
    'team.teamSubtitle': 'Опытные специалисты в области технологий, операций и стратегического развития',
    'glossary.title': 'Инвестиционный Глоссарий',
    'glossary.subtitle': 'Основные финансовые термины и аббревиатуры',
    'glossary.search': 'Поиск терминов...',
  },
  uk: {
    'nav.home': 'Головна',
    'nav.projects': 'Проекти',
    'nav.forInvestors': 'Для Інвесторів',
    'nav.aboutUs': 'Про Нас',
    'nav.team': 'Команда',
    'nav.contact': 'Контакти',
    'nav.news': 'Новини та Статті',
    'nav.howItWorks': 'Як Це Працює',
    'nav.investorInfo': 'Інформація для Інвесторів',
    'common.learnMore': 'Дізнатися Більше',
    'common.viewDetails': 'Детальніше',
    'common.viewAll': 'Переглянути Все',
    'common.submit': 'Надіслати',
    'common.cancel': 'Скасувати',
    'common.save': 'Зберегти',
    'common.delete': 'Видалити',
    'common.edit': 'Редагувати',
    'common.back': 'Назад',
    'common.loading': 'Завантаження...',
    'common.search': 'Пошук',
    'common.filter': 'Фільтр',
    'common.close': 'Закрити',
    'common.download': 'Завантажити',
    'common.readMore': 'Читати Далі',
    'hero.title': 'Створення Проектів Реальної Економіки та Передових Технологій',
    'hero.subtitle': 'Мультисекторний портфель у сферах охорони здоров\'я, сільського господарства, харчових систем та ШІ інфраструктури',
    'hero.cta1': 'Вивчити Проекти',
    'hero.cta2': 'Інвестиційна Інформація',
    'projects.title': 'Наші Проекти',
    'projects.subtitle': 'Вивчіть наш різноманітний портфель технологічних та реально-економічних проектів',
    'projects.featured': 'Обрані Проекти',
    'projects.viewAll': 'Переглянути Всі Проекти',
    'projects.status.open': 'Відкритий',
    'projects.status.closed': 'Закритий',
    'projects.status.comingSoon': 'Незабаром',
    'projects.submitInterest': 'Виразити Інтерес',
    'projects.learnMore': 'Дізнатися Більше',
    'projects.category': 'Категорія',
    'projects.location': 'Розташування',
    'form.name': 'Ім\'я',
    'form.email': 'Електронна пошта',
    'form.phone': 'Телефон',
    'form.country': 'Країна',
    'form.message': 'Повідомлення',
    'form.comments': 'Коментарі',
    'form.interestLevel': 'Приблизний рівень інтересу (необов\'язково, необов\'язковий)',
    'form.required': 'Обов\'язково',
    'form.optional': 'Необов\'язково',
    'form.submitRequest': 'Надіслати Запит Інформації',
    'form.sending': 'Надсилання...',
    'form.success': 'Дякуємо! Ваш запит отримано. Ми зв\'яжемося з вами найближчим часом.',
    'form.error': 'Щось пішло не так. Будь ласка, спробуйте ще раз.',
    'form.disclaimer': 'Це необов\'язкове вираження інтересу і не є зобов\'язанням чи пропозицією.',
    'disclaimer.investment': 'Digital Invest Inc. не є інвестиційним консультантом, брокером-дилером, краудфандинговою платформою або публічним ринком. Участь у будь-якому проекті здійснюється в приватному порядку, офлайн та лише для відповідних фізичних або юридичних осіб після перевірки.',
    'disclaimer.global': 'Digital Invest Inc. є приватною компанією. Цей сайт призначений лише для інформаційних цілей і не є пропозицією про продаж, запрошенням до покупки або рекомендацією будь-яких цінних паперів або фінансових інструментів.',
    'disclaimer.noGuarantees': 'Нічого на цьому сайті не слід розглядати як інвестиційну, юридичну, податкову або фінансову консультацію. Жодних гарантій, обіцянок або прогнозованих доходів не надається і не передбачається.',
    'footer.company': 'Компанія',
    'footer.projects': 'Проекти',
    'footer.legal': 'Юридичні Питання',
    'footer.press': 'Преса та Ресурси',
    'footer.contact': 'Контакти',
    'footer.description': 'Створення та масштабування проектів реальної економіки, ШІ, виробництва та охорони здоров\'я по всіх Сполучених Штатах.',
    'footer.copyright': '© 2025 Digital Invest Inc. Всі права захищені.',
    'team.title': 'Наша Команда',
    'team.subtitle': 'Познайомтеся з професіоналами, які ведуть інновації та зростання в Digital Invest Inc.',
    'team.founderTitle': 'Виконавче Керівництво',
    'team.teamMembers': 'Члени Команди',
    'team.teamSubtitle': 'Досвідчені фахівці в галузі технологій, операцій та стратегічного розвитку',
    'glossary.title': 'Інвестиційний Глосарій',
    'glossary.subtitle': 'Основні фінансові терміни та абревіатури',
    'glossary.search': 'Пошук термінів...',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.projects': 'Proyectos',
    'nav.forInvestors': 'Para Inversores',
    'nav.aboutUs': 'Sobre Nosotros',
    'nav.team': 'Equipo',
    'nav.contact': 'Contacto',
    'nav.news': 'Noticias e Insights',
    'nav.howItWorks': 'Cómo Funciona',
    'nav.investorInfo': 'Información para Inversores',
    'common.learnMore': 'Saber Más',
    'common.viewDetails': 'Ver Detalles',
    'common.viewAll': 'Ver Todo',
    'common.submit': 'Enviar',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.back': 'Volver',
    'common.loading': 'Cargando...',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.close': 'Cerrar',
    'common.download': 'Descargar',
    'common.readMore': 'Leer Más',
    'hero.title': 'Construyendo Proyectos de Economía Real y Tecnología Avanzada',
    'hero.subtitle': 'Cartera multisectorial en salud, agricultura, sistemas alimentarios e infraestructura de IA',
    'hero.cta1': 'Explorar Proyectos',
    'hero.cta2': 'Información de Inversión',
    'projects.title': 'Nuestros Proyectos',
    'projects.subtitle': 'Explore nuestra cartera diversa de tecnología y proyectos de economía real',
    'projects.featured': 'Proyectos Destacados',
    'projects.viewAll': 'Ver Todos los Proyectos',
    'projects.status.open': 'Abierto',
    'projects.status.closed': 'Cerrado',
    'projects.status.comingSoon': 'Próximamente',
    'projects.submitInterest': 'Expresar Interés',
    'projects.learnMore': 'Saber Más',
    'projects.category': 'Categoría',
    'projects.location': 'Ubicación',
    'form.name': 'Nombre',
    'form.email': 'Correo electrónico',
    'form.phone': 'Teléfono',
    'form.country': 'País',
    'form.message': 'Mensaje',
    'form.comments': 'Comentarios',
    'form.interestLevel': 'Nivel de interés aproximado (opcional, no vinculante)',
    'form.required': 'Requerido',
    'form.optional': 'Opcional',
    'form.submitRequest': 'Enviar Solicitud de Información',
    'form.sending': 'Enviando...',
    'form.success': '¡Gracias! Su solicitud ha sido recibida. Nos pondremos en contacto pronto.',
    'form.error': 'Algo salió mal. Por favor, inténtelo de nuevo.',
    'form.disclaimer': 'Esta es una expresión de interés no vinculante y no constituye un compromiso u oferta.',
    'disclaimer.investment': 'Digital Invest Inc. no es un asesor de inversiones, corredor de bolsa, plataforma de crowdfunding o mercado público. La participación en cualquier proyecto se maneja de forma privada, fuera de línea y solo para personas o entidades elegibles después de la debida diligencia.',
    'disclaimer.global': 'Digital Invest Inc. es una entidad privada. Este sitio web es solo para fines informativos y no constituye una oferta de venta, una solicitud de compra o una recomendación de valores o instrumentos financieros.',
    'disclaimer.noGuarantees': 'Nada en este sitio web debe interpretarse como asesoramiento de inversión, legal, fiscal o financiero. No se hacen ni implican garantías, promesas o rendimientos futuros.',
    'footer.company': 'Empresa',
    'footer.projects': 'Proyectos',
    'footer.legal': 'Legal y Riesgo',
    'footer.press': 'Prensa y Recursos',
    'footer.contact': 'Contacto',
    'footer.description': 'Construyendo y escalando proyectos de economía real, IA, manufactura y tecnología de salud en Estados Unidos.',
    'footer.copyright': '© 2025 Digital Invest Inc. Todos los derechos reservados.',
    'team.title': 'Nuestro Equipo',
    'team.subtitle': 'Conozca a los profesionales que impulsan la innovación y el crecimiento en Digital Invest Inc.',
    'team.founderTitle': 'Liderazgo Ejecutivo',
    'team.teamMembers': 'Miembros del Equipo',
    'team.teamSubtitle': 'Profesionales experimentados en tecnología, operaciones y desarrollo estratégico',
    'glossary.title': 'Glosario de Inversiones',
    'glossary.subtitle': 'Términos financieros esenciales y abreviaturas',
    'glossary.search': 'Buscar términos...',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.projects': 'Projets',
    'nav.forInvestors': 'Pour les Investisseurs',
    'nav.aboutUs': 'À Propos',
    'nav.team': 'Équipe',
    'nav.contact': 'Contact',
    'nav.news': 'Actualités et Insights',
    'nav.howItWorks': 'Comment Ça Marche',
    'nav.investorInfo': 'Informations pour Investisseurs',
    'common.learnMore': 'En Savoir Plus',
    'common.viewDetails': 'Voir les Détails',
    'common.viewAll': 'Voir Tout',
    'common.submit': 'Soumettre',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.back': 'Retour',
    'common.loading': 'Chargement...',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.close': 'Fermer',
    'common.download': 'Télécharger',
    'common.readMore': 'Lire Plus',
    'hero.title': 'Construire des Projets d\'Économie Réelle et de Technologie Avancée',
    'hero.subtitle': 'Portefeuille multisectoriel dans la santé, l\'agriculture, les systèmes alimentaires et l\'infrastructure IA',
    'hero.cta1': 'Explorer les Projets',
    'hero.cta2': 'Informations sur l\'Investissement',
    'projects.title': 'Nos Projets',
    'projects.subtitle': 'Explorez notre portefeuille diversifié de technologie et de projets d\'économie réelle',
    'projects.featured': 'Projets en Vedette',
    'projects.viewAll': 'Voir Tous les Projets',
    'projects.status.open': 'Ouvert',
    'projects.status.closed': 'Fermé',
    'projects.status.comingSoon': 'Bientôt Disponible',
    'projects.submitInterest': 'Exprimer son Intérêt',
    'projects.learnMore': 'En Savoir Plus',
    'projects.category': 'Catégorie',
    'projects.location': 'Emplacement',
    'form.name': 'Nom',
    'form.email': 'E-mail',
    'form.phone': 'Téléphone',
    'form.country': 'Pays',
    'form.message': 'Message',
    'form.comments': 'Commentaires',
    'form.interestLevel': 'Niveau d\'intérêt approximatif (optionnel, non contraignant)',
    'form.required': 'Requis',
    'form.optional': 'Optionnel',
    'form.submitRequest': 'Soumettre une Demande d\'Information',
    'form.sending': 'Envoi en cours...',
    'form.success': 'Merci ! Votre demande a été reçue. Nous vous contacterons bientôt.',
    'form.error': 'Quelque chose s\'est mal passé. Veuillez réessayer.',
    'form.disclaimer': 'Ceci est une expression d\'intérêt non contraignante et ne constitue pas un engagement ou une offre.',
    'disclaimer.investment': 'Digital Invest Inc. n\'est pas un conseiller en investissement, un courtier, une plateforme de financement participatif ou un marché public. La participation à tout projet est traitée en privé, hors ligne et uniquement pour les personnes ou entités éligibles après une diligence raisonnable.',
    'disclaimer.global': 'Digital Invest Inc. est une entité privée. Ce site Web est à des fins d\'information uniquement et ne constitue pas une offre de vente, une sollicitation d\'achat ou une recommandation de titres ou d\'instruments financiers.',
    'disclaimer.noGuarantees': 'Rien sur ce site Web ne doit être interprété comme un conseil en investissement, juridique, fiscal ou financier. Aucune garantie, promesse ou rendement futur n\'est fait ou implicite.',
    'footer.company': 'Entreprise',
    'footer.projects': 'Projets',
    'footer.legal': 'Juridique et Risques',
    'footer.press': 'Presse et Ressources',
    'footer.contact': 'Contact',
    'footer.description': 'Construire et développer des projets d\'économie réelle, d\'IA, de fabrication et de technologie de santé aux États-Unis.',
    'footer.copyright': '© 2025 Digital Invest Inc. Tous droits réservés.',
    'team.title': 'Notre Équipe',
    'team.subtitle': 'Rencontrez les professionnels qui stimulent l\'innovation et la croissance chez Digital Invest Inc.',
    'team.founderTitle': 'Direction Exécutive',
    'team.teamMembers': 'Membres de l\'Équipe',
    'team.teamSubtitle': 'Professionnels expérimentés en technologie, opérations et développement stratégique',
    'glossary.title': 'Glossaire d\'Investissement',
    'glossary.subtitle': 'Termes financiers essentiels et abréviations',
    'glossary.search': 'Rechercher des termes...',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.projects': 'Projekte',
    'nav.forInvestors': 'Für Investoren',
    'nav.aboutUs': 'Über Uns',
    'nav.team': 'Team',
    'nav.contact': 'Kontakt',
    'nav.news': 'News & Insights',
    'nav.howItWorks': 'Wie es funktioniert',
    'nav.investorInfo': 'Investor Information',
    'common.learnMore': 'Mehr Erfahren',
    'common.viewDetails': 'Details Ansehen',
    'common.viewAll': 'Alle Ansehen',
    'common.submit': 'Einreichen',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.back': 'Zurück',
    'common.loading': 'Wird geladen...',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.close': 'Schließen',
    'common.download': 'Herunterladen',
    'common.readMore': 'Weiterlesen',
    'hero.title': 'Aufbau von Realwirtschafts- und Hochtechnologieprojekten',
    'hero.subtitle': 'Multi-Sektor-Portfolio in Gesundheit, Landwirtschaft, Lebensmittelsystemen und KI-Infrastruktur',
    'hero.cta1': 'Projekte Erkunden',
    'hero.cta2': 'Investitionsinformationen',
    'projects.title': 'Unsere Projekte',
    'projects.subtitle': 'Erkunden Sie unser vielfältiges Portfolio von Technologie- und Realwirtschaftsprojekten',
    'projects.featured': 'Vorgestellte Projekte',
    'projects.viewAll': 'Alle Projekte Ansehen',
    'projects.status.open': 'Offen',
    'projects.status.closed': 'Geschlossen',
    'projects.status.comingSoon': 'Demnächst',
    'projects.submitInterest': 'Interesse Bekunden',
    'projects.learnMore': 'Mehr Erfahren',
    'projects.category': 'Kategorie',
    'projects.location': 'Standort',
    'form.name': 'Name',
    'form.email': 'E-Mail',
    'form.phone': 'Telefon',
    'form.country': 'Land',
    'form.message': 'Nachricht',
    'form.comments': 'Kommentare',
    'form.interestLevel': 'Ungefähres Interessenniveau (optional, unverbindlich)',
    'form.required': 'Erforderlich',
    'form.optional': 'Optional',
    'form.submitRequest': 'Informationsanfrage Senden',
    'form.sending': 'Wird gesendet...',
    'form.success': 'Vielen Dank! Ihre Anfrage wurde empfangen. Wir werden Sie in Kürze kontaktieren.',
    'form.error': 'Etwas ist schief gelaufen. Bitte versuchen Sie es erneut.',
    'form.disclaimer': 'Dies ist eine unverbindliche Interessenbekundung und stellt keine Verpflichtung oder Angebot dar.',
    'disclaimer.investment': 'Digital Invest Inc. ist kein Anlageberater, Broker-Dealer, Crowdfunding-Plattform oder öffentlicher Marktplatz. Die Teilnahme an einem Projekt erfolgt privat, offline und nur für geeignete Personen oder Unternehmen nach Due Diligence.',
    'disclaimer.global': 'Digital Invest Inc. ist eine private Einrichtung. Diese Website dient nur zu Informationszwecken und stellt kein Verkaufsangebot, keine Kaufaufforderung oder Empfehlung von Wertpapieren oder Finanzinstrumenten dar.',
    'disclaimer.noGuarantees': 'Nichts auf dieser Website sollte als Anlage-, Rechts-, Steuer- oder Finanzberatung ausgelegt werden. Es werden keine Garantien, Versprechen oder zukünftige Renditen gemacht oder impliziert.',
    'footer.company': 'Unternehmen',
    'footer.projects': 'Projekte',
    'footer.legal': 'Rechtliches & Risiko',
    'footer.press': 'Presse & Ressourcen',
    'footer.contact': 'Kontakt',
    'footer.description': 'Aufbau und Skalierung von Realwirtschafts-, KI-, Fertigungs- und Gesundheitstechnologieprojekten in den Vereinigten Staaten.',
    'footer.copyright': '© 2025 Digital Invest Inc. Alle Rechte vorbehalten.',
    'team.title': 'Unser Team',
    'team.subtitle': 'Lernen Sie die Fachleute kennen, die Innovation und Wachstum bei Digital Invest Inc. vorantreiben.',
    'team.founderTitle': 'Geschäftsführung',
    'team.teamMembers': 'Teammitglieder',
    'team.teamSubtitle': 'Erfahrene Fachleute in Technologie, Betrieb und strategischer Entwicklung',
    'glossary.title': 'Investment-Glossar',
    'glossary.subtitle': 'Wesentliche Finanzbegriffe und Abkürzungen',
    'glossary.search': 'Begriffe suchen...',
  },
  zh: {
    'nav.home': '首页',
    'nav.projects': '项目',
    'nav.forInvestors': '投资者',
    'nav.aboutUs': '关于我们',
    'nav.team': '团队',
    'nav.contact': '联系方式',
    'nav.news': '新闻与洞察',
    'nav.howItWorks': '工作原理',
    'nav.investorInfo': '投资者信息',
    'common.learnMore': '了解更多',
    'common.viewDetails': '查看详情',
    'common.viewAll': '查看全部',
    'common.submit': '提交',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.back': '返回',
    'common.loading': '加载中...',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.close': '关闭',
    'common.download': '下载',
    'common.readMore': '阅读更多',
    'hero.title': '构建实体经济和先进技术项目',
    'hero.subtitle': '跨健康、农业、食品系统和人工智能基础设施的多部门投资组合',
    'hero.cta1': '探索项目',
    'hero.cta2': '投资信息',
    'projects.title': '我们的项目',
    'projects.subtitle': '探索我们多样化的技术和实体经济项目组合',
    'projects.featured': '精选项目',
    'projects.viewAll': '查看所有项目',
    'projects.status.open': '开放',
    'projects.status.closed': '关闭',
    'projects.status.comingSoon': '即将推出',
    'projects.submitInterest': '提交兴趣',
    'projects.learnMore': '了解更多',
    'projects.category': '类别',
    'projects.location': '位置',
    'form.name': '姓名',
    'form.email': '电子邮件',
    'form.phone': '电话',
    'form.country': '国家',
    'form.message': '消息',
    'form.comments': '评论',
    'form.interestLevel': '大致兴趣水平（可选，无约束力）',
    'form.required': '必填',
    'form.optional': '可选',
    'form.submitRequest': '提交信息请求',
    'form.sending': '发送中...',
    'form.success': '谢谢！您的请求已收到。我们将尽快与您联系。',
    'form.error': '出现问题。请重试。',
    'form.disclaimer': '这是一个无约束力的兴趣表达，不构成承诺或要约。',
    'disclaimer.investment': 'Digital Invest Inc. 不是投资顾问、经纪商、众筹平台或公共市场。参与任何项目均为私下进行，离线处理，仅限符合条件的个人或实体在尽职调查后参与。',
    'disclaimer.global': 'Digital Invest Inc. 是一家私人实体。本网站仅供参考，不构成出售要约、购买邀请或推荐任何证券或金融工具。',
    'disclaimer.noGuarantees': '本网站上的任何内容均不应被解释为投资、法律、税务或财务建议。不作出或暗示任何保证、承诺或前瞻性回报。',
    'footer.company': '公司',
    'footer.projects': '项目',
    'footer.legal': '法律与风险',
    'footer.press': '新闻与资源',
    'footer.contact': '联系方式',
    'footer.description': '在美国各地构建和扩展实体经济、人工智能、制造业和健康技术项目。',
    'footer.copyright': '© 2025 Digital Invest Inc. 保留所有权利。',
    'team.title': '我们的团队',
    'team.subtitle': '认识推动 Digital Invest Inc. 创新和增长的专业人士。',
    'team.founderTitle': '执行领导层',
    'team.teamMembers': '团队成员',
    'team.teamSubtitle': '技术、运营和战略发展领域的资深专业人士',
    'glossary.title': '投资术语表',
    'glossary.subtitle': '基本金融术语和缩写',
    'glossary.search': '搜索术语...',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.projects': 'プロジェクト',
    'nav.forInvestors': '投資家向け',
    'nav.aboutUs': '会社概要',
    'nav.team': 'チーム',
    'nav.contact': 'お問い合わせ',
    'nav.news': 'ニュース＆インサイト',
    'nav.howItWorks': '仕組み',
    'nav.investorInfo': '投資家情報',
    'common.learnMore': '詳細を見る',
    'common.viewDetails': '詳細を表示',
    'common.viewAll': 'すべて表示',
    'common.submit': '送信',
    'common.cancel': 'キャンセル',
    'common.save': '保存',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.back': '戻る',
    'common.loading': '読み込み中...',
    'common.search': '検索',
    'common.filter': 'フィルター',
    'common.close': '閉じる',
    'common.download': 'ダウンロード',
    'common.readMore': '続きを読む',
    'hero.title': '実体経済と先進技術プロジェクトの構築',
    'hero.subtitle': '医療、農業、食品システム、AI インフラストラクチャにわたるマルチセクターポートフォリオ',
    'hero.cta1': 'プロジェクトを探索',
    'hero.cta2': '投資情報',
    'projects.title': '私たちのプロジェクト',
    'projects.subtitle': '技術と実体経済プロジェクトの多様なポートフォリオを探索',
    'projects.featured': '注目のプロジェクト',
    'projects.viewAll': 'すべてのプロジェクトを表示',
    'projects.status.open': 'オープン',
    'projects.status.closed': 'クローズ',
    'projects.status.comingSoon': '近日公開',
    'projects.submitInterest': '興味を示す',
    'projects.learnMore': '詳細を見る',
    'projects.category': 'カテゴリー',
    'projects.location': '場所',
    'form.name': '名前',
    'form.email': 'メールアドレス',
    'form.phone': '電話番号',
    'form.country': '国',
    'form.message': 'メッセージ',
    'form.comments': 'コメント',
    'form.interestLevel': 'おおよその関心レベル（任意、拘束力なし）',
    'form.required': '必須',
    'form.optional': '任意',
    'form.submitRequest': '情報リクエストを送信',
    'form.sending': '送信中...',
    'form.success': 'ありがとうございます！リクエストを受け付けました。まもなくご連絡いたします。',
    'form.error': '問題が発生しました。もう一度お試しください。',
    'form.disclaimer': 'これは拘束力のない関心表明であり、約束または申し出を構成するものではありません。',
    'disclaimer.investment': 'Digital Invest Inc. は投資アドバイザー、ブローカー・ディーラー、クラウドファンディングプラットフォーム、または公開市場ではありません。プロジェクトへの参加は、デューデリジェンス後の適格な個人または団体に限り、私的にオフラインで処理されます。',
    'disclaimer.global': 'Digital Invest Inc. は民間企業です。このウェブサイトは情報提供のみを目的としており、売却の申し出、購入の勧誘、または証券や金融商品の推奨を構成するものではありません。',
    'disclaimer.noGuarantees': 'このウェブサイト上のいかなる内容も、投資、法律、税務、または財務に関するアドバイスとして解釈されるべきではありません。保証、約束、または将来のリターンは行われたり暗示されたりしていません。',
    'footer.company': '会社',
    'footer.projects': 'プロジェクト',
    'footer.legal': '法律とリスク',
    'footer.press': 'プレスとリソース',
    'footer.contact': 'お問い合わせ',
    'footer.description': '米国全体で実体経済、AI、製造、医療技術プロジェクトを構築および拡張。',
    'footer.copyright': '© 2025 Digital Invest Inc. すべての権利を保有。',
    'team.title': '私たちのチーム',
    'team.subtitle': 'Digital Invest Inc. のイノベーションと成長を推進する専門家をご紹介します。',
    'team.founderTitle': '経営陣',
    'team.teamMembers': 'チームメンバー',
    'team.teamSubtitle': '技術、運用、戦略的開発における経験豊富な専門家',
    'glossary.title': '投資用語集',
    'glossary.subtitle': '基本的な金融用語と略語',
    'glossary.search': '用語を検索...',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.projects': 'المشاريع',
    'nav.forInvestors': 'للمستثمرين',
    'nav.aboutUs': 'معلومات عنا',
    'nav.team': 'الفريق',
    'nav.contact': 'اتصل بنا',
    'nav.news': 'الأخبار والرؤى',
    'nav.howItWorks': 'كيف يعمل',
    'nav.investorInfo': 'معلومات المستثمر',
    'common.learnMore': 'اعرف المزيد',
    'common.viewDetails': 'عرض التفاصيل',
    'common.viewAll': 'عرض الكل',
    'common.submit': 'إرسال',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.back': 'رجوع',
    'common.loading': 'جاري التحميل...',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.close': 'إغلاق',
    'common.download': 'تنزيل',
    'common.readMore': 'اقرأ المزيد',
    'hero.title': 'بناء مشاريع الاقتصاد الحقيقي والتكنولوجيا المتقدمة',
    'hero.subtitle': 'محفظة متعددة القطاعات عبر الصحة والزراعة وأنظمة الغذاء والبنية التحتية للذكاء الاصطناعي',
    'hero.cta1': 'استكشاف المشاريع',
    'hero.cta2': 'معلومات الاستثمار',
    'projects.title': 'مشاريعنا',
    'projects.subtitle': 'استكشف محفظتنا المتنوعة من التكنولوجيا ومشاريع الاقتصاد الحقيقي',
    'projects.featured': 'المشاريع المميزة',
    'projects.viewAll': 'عرض جميع المشاريع',
    'projects.status.open': 'مفتوح',
    'projects.status.closed': 'مغلق',
    'projects.status.comingSoon': 'قريبًا',
    'projects.submitInterest': 'إبداء الاهتمام',
    'projects.learnMore': 'اعرف المزيد',
    'projects.category': 'الفئة',
    'projects.location': 'الموقع',
    'form.name': 'الاسم',
    'form.email': 'البريد الإلكتروني',
    'form.phone': 'الهاتف',
    'form.country': 'البلد',
    'form.message': 'رسالة',
    'form.comments': 'التعليقات',
    'form.interestLevel': 'مستوى الاهتمام التقريبي (اختياري، غير ملزم)',
    'form.required': 'مطلوب',
    'form.optional': 'اختياري',
    'form.submitRequest': 'إرسال طلب معلومات',
    'form.sending': 'جاري الإرسال...',
    'form.success': 'شكرًا لك! تم استلام طلبك. سنتواصل معك قريبًا.',
    'form.error': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    'form.disclaimer': 'هذا تعبير غير ملزم عن الاهتمام ولا يشكل التزامًا أو عرضًا.',
    'disclaimer.investment': 'Digital Invest Inc. ليست مستشارًا استثماريًا أو وسيطًا تجاريًا أو منصة تمويل جماعي أو سوقًا عامة. تتم المشاركة في أي مشروع بشكل خاص وغير متصل وفقط للأفراد أو الكيانات المؤهلة بعد العناية الواجبة.',
    'disclaimer.global': 'Digital Invest Inc. كيان خاص. هذا الموقع للأغراض الإعلامية فقط ولا يشكل عرضًا للبيع أو دعوة للشراء أو توصية بأي أوراق مالية أو أدوات مالية.',
    'disclaimer.noGuarantees': 'لا ينبغي تفسير أي شيء على هذا الموقع على أنه استثمار أو نصيحة قانونية أو ضريبية أو مالية. لا تُقدم أو تُضمن أي ضمانات أو وعود أو عوائد مستقبلية.',
    'footer.company': 'الشركة',
    'footer.projects': 'المشاريع',
    'footer.legal': 'القانونية والمخاطر',
    'footer.press': 'الصحافة والموارد',
    'footer.contact': 'اتصل بنا',
    'footer.description': 'بناء وتوسيع نطاق مشاريع الاقتصاد الحقيقي والذكاء الاصطناعي والتصنيع والتكنولوجيا الصحية في جميع أنحاء الولايات المتحدة.',
    'footer.copyright': '© 2025 Digital Invest Inc. جميع الحقوق محفوظة.',
    'team.title': 'فريقنا',
    'team.subtitle': 'تعرف على المحترفين الذين يقودون الابتكار والنمو في Digital Invest Inc.',
    'team.founderTitle': 'القيادة التنفيذية',
    'team.teamMembers': 'أعضاء الفريق',
    'team.teamSubtitle': 'محترفون ذوو خبرة في التكنولوجيا والعمليات والتطوير الاستراتيجي',
    'glossary.title': 'مسرد الاستثمار',
    'glossary.subtitle': 'المصطلحات المالية الأساسية والاختصارات',
    'glossary.search': 'البحث عن المصطلحات...',
  },
  pt: {
    'nav.home': 'Início',
    'nav.projects': 'Projetos',
    'nav.forInvestors': 'Para Investidores',
    'nav.aboutUs': 'Sobre Nós',
    'nav.team': 'Equipe',
    'nav.contact': 'Contato',
    'nav.news': 'Notícias e Insights',
    'nav.howItWorks': 'Como Funciona',
    'nav.investorInfo': 'Informações para Investidores',
    'common.learnMore': 'Saiba Mais',
    'common.viewDetails': 'Ver Detalhes',
    'common.viewAll': 'Ver Tudo',
    'common.submit': 'Enviar',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.back': 'Voltar',
    'common.loading': 'Carregando...',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.close': 'Fechar',
    'common.download': 'Baixar',
    'common.readMore': 'Leia Mais',
    'hero.title': 'Construindo Projetos de Economia Real e Tecnologia Avançada',
    'hero.subtitle': 'Portfólio multissetorial em saúde, agricultura, sistemas alimentares e infraestrutura de IA',
    'hero.cta1': 'Explorar Projetos',
    'hero.cta2': 'Informações de Investimento',
    'projects.title': 'Nossos Projetos',
    'projects.subtitle': 'Explore nosso portfólio diversificado de tecnologia e projetos de economia real',
    'projects.featured': 'Projetos em Destaque',
    'projects.viewAll': 'Ver Todos os Projetos',
    'projects.status.open': 'Aberto',
    'projects.status.closed': 'Fechado',
    'projects.status.comingSoon': 'Em Breve',
    'projects.submitInterest': 'Manifestar Interesse',
    'projects.learnMore': 'Saiba Mais',
    'projects.category': 'Categoria',
    'projects.location': 'Localização',
    'form.name': 'Nome',
    'form.email': 'E-mail',
    'form.phone': 'Telefone',
    'form.country': 'País',
    'form.message': 'Mensagem',
    'form.comments': 'Comentários',
    'form.interestLevel': 'Nível de interesse aproximado (opcional, não vinculativo)',
    'form.required': 'Obrigatório',
    'form.optional': 'Opcional',
    'form.submitRequest': 'Enviar Solicitação de Informações',
    'form.sending': 'Enviando...',
    'form.success': 'Obrigado! Sua solicitação foi recebida. Entraremos em contato em breve.',
    'form.error': 'Algo deu errado. Por favor, tente novamente.',
    'form.disclaimer': 'Esta é uma expressão de interesse não vinculativa e não constitui um compromisso ou oferta.',
    'disclaimer.investment': 'Digital Invest Inc. não é um consultor de investimentos, corretor, plataforma de crowdfunding ou mercado público. A participação em qualquer projeto é tratada de forma privada, offline e apenas para indivíduos ou entidades elegíveis após due diligence.',
    'disclaimer.global': 'Digital Invest Inc. é uma entidade privada. Este site é apenas para fins informativos e não constitui uma oferta de venda, uma solicitação de compra ou uma recomendação de valores mobiliários ou instrumentos financeiros.',
    'disclaimer.noGuarantees': 'Nada neste site deve ser interpretado como investimento, aconselhamento jurídico, fiscal ou financeiro. Nenhuma garantia, promessa ou retorno futuro é feito ou implícito.',
    'footer.company': 'Empresa',
    'footer.projects': 'Projetos',
    'footer.legal': 'Legal e Risco',
    'footer.press': 'Imprensa e Recursos',
    'footer.contact': 'Contato',
    'footer.description': 'Construindo e escalando projetos de economia real, IA, manufatura e tecnologia de saúde nos Estados Unidos.',
    'footer.copyright': '© 2025 Digital Invest Inc. Todos os direitos reservados.',
    'team.title': 'Nossa Equipe',
    'team.subtitle': 'Conheça os profissionais que impulsionam a inovação e o crescimento na Digital Invest Inc.',
    'team.founderTitle': 'Liderança Executiva',
    'team.teamMembers': 'Membros da Equipe',
    'team.teamSubtitle': 'Profissionais experientes em tecnologia, operações e desenvolvimento estratégico',
    'glossary.title': 'Glossário de Investimentos',
    'glossary.subtitle': 'Termos financeiros essenciais e abreviações',
    'glossary.search': 'Pesquisar termos...',
  },
  it: {
    'nav.home': 'Home',
    'nav.projects': 'Progetti',
    'nav.forInvestors': 'Per Investitori',
    'nav.aboutUs': 'Chi Siamo',
    'nav.team': 'Team',
    'nav.contact': 'Contatti',
    'nav.news': 'Notizie e Approfondimenti',
    'nav.howItWorks': 'Come Funziona',
    'nav.investorInfo': 'Informazioni per Investitori',
    'common.learnMore': 'Scopri di Più',
    'common.viewDetails': 'Vedi Dettagli',
    'common.viewAll': 'Vedi Tutto',
    'common.submit': 'Invia',
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.back': 'Indietro',
    'common.loading': 'Caricamento...',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.close': 'Chiudi',
    'common.download': 'Scarica',
    'common.readMore': 'Leggi di Più',
    'hero.title': 'Costruire Progetti di Economia Reale e Tecnologia Avanzata',
    'hero.subtitle': 'Portfolio multisettoriale in salute, agricoltura, sistemi alimentari e infrastruttura IA',
    'hero.cta1': 'Esplora i Progetti',
    'hero.cta2': 'Informazioni sugli Investimenti',
    'projects.title': 'I Nostri Progetti',
    'projects.subtitle': 'Esplora il nostro portfolio diversificato di tecnologia e progetti di economia reale',
    'projects.featured': 'Progetti in Evidenza',
    'projects.viewAll': 'Vedi Tutti i Progetti',
    'projects.status.open': 'Aperto',
    'projects.status.closed': 'Chiuso',
    'projects.status.comingSoon': 'Prossimamente',
    'projects.submitInterest': 'Manifesta Interesse',
    'projects.learnMore': 'Scopri di Più',
    'projects.category': 'Categoria',
    'projects.location': 'Posizione',
    'form.name': 'Nome',
    'form.email': 'Email',
    'form.phone': 'Telefono',
    'form.country': 'Paese',
    'form.message': 'Messaggio',
    'form.comments': 'Commenti',
    'form.interestLevel': 'Livello di interesse approssimativo (opzionale, non vincolante)',
    'form.required': 'Obbligatorio',
    'form.optional': 'Facoltativo',
    'form.submitRequest': 'Invia Richiesta di Informazioni',
    'form.sending': 'Invio in corso...',
    'form.success': 'Grazie! La tua richiesta è stata ricevuta. Ti contatteremo presto.',
    'form.error': 'Qualcosa è andato storto. Per favore riprova.',
    'form.disclaimer': 'Questa è un\'espressione di interesse non vincolante e non costituisce un impegno o un\'offerta.',
    'disclaimer.investment': 'Digital Invest Inc. non è un consulente di investimento, intermediario, piattaforma di crowdfunding o mercato pubblico. La partecipazione a qualsiasi progetto viene gestita privatamente, offline e solo per individui o entità idonei dopo due diligence.',
    'disclaimer.global': 'Digital Invest Inc. è un\'entità privata. Questo sito web è solo a scopo informativo e non costituisce un\'offerta di vendita, una sollecitazione all\'acquisto o una raccomandazione di titoli o strumenti finanziari.',
    'disclaimer.noGuarantees': 'Nulla su questo sito web deve essere interpretato come investimento, consulenza legale, fiscale o finanziaria. Non vengono fatte o implicite garanzie, promesse o rendimenti futuri.',
    'footer.company': 'Azienda',
    'footer.projects': 'Progetti',
    'footer.legal': 'Legale e Rischio',
    'footer.press': 'Stampa e Risorse',
    'footer.contact': 'Contatti',
    'footer.description': 'Costruire e scalare progetti di economia reale, IA, manifattura e tecnologia sanitaria negli Stati Uniti.',
    'footer.copyright': '© 2025 Digital Invest Inc. Tutti i diritti riservati.',
    'team.title': 'Il Nostro Team',
    'team.subtitle': 'Incontra i professionisti che guidano l\'innovazione e la crescita in Digital Invest Inc.',
    'team.founderTitle': 'Leadership Esecutiva',
    'team.teamMembers': 'Membri del Team',
    'team.teamSubtitle': 'Professionisti esperti in tecnologia, operazioni e sviluppo strategico',
    'glossary.title': 'Glossario degli Investimenti',
    'glossary.subtitle': 'Termini finanziari essenziali e abbreviazioni',
    'glossary.search': 'Cerca termini...',
  },
  nl: {
    'nav.home': 'Home',
    'nav.projects': 'Projecten',
    'nav.forInvestors': 'Voor Investeerders',
    'nav.aboutUs': 'Over Ons',
    'nav.team': 'Team',
    'nav.contact': 'Contact',
    'nav.news': 'Nieuws & Inzichten',
    'nav.howItWorks': 'Hoe Het Werkt',
    'nav.investorInfo': 'Investeerdersinformatie',
    'common.learnMore': 'Meer Informatie',
    'common.viewDetails': 'Details Bekijken',
    'common.viewAll': 'Alles Bekijken',
    'common.submit': 'Verzenden',
    'common.cancel': 'Annuleren',
    'common.save': 'Opslaan',
    'common.delete': 'Verwijderen',
    'common.edit': 'Bewerken',
    'common.back': 'Terug',
    'common.loading': 'Laden...',
    'common.search': 'Zoeken',
    'common.filter': 'Filteren',
    'common.close': 'Sluiten',
    'common.download': 'Downloaden',
    'common.readMore': 'Lees Meer',
    'hero.title': 'Bouwen van Reële Economie en Geavanceerde Technologie Projecten',
    'hero.subtitle': 'Multi-sector portfolio in gezondheid, landbouw, voedselsystemen en AI-infrastructuur',
    'hero.cta1': 'Projecten Verkennen',
    'hero.cta2': 'Investeringsinformatie',
    'projects.title': 'Onze Projecten',
    'projects.subtitle': 'Verken onze diverse portfolio van technologie en reële economie projecten',
    'projects.featured': 'Uitgelichte Projecten',
    'projects.viewAll': 'Alle Projecten Bekijken',
    'projects.status.open': 'Open',
    'projects.status.closed': 'Gesloten',
    'projects.status.comingSoon': 'Binnenkort',
    'projects.submitInterest': 'Interesse Tonen',
    'projects.learnMore': 'Meer Informatie',
    'projects.category': 'Categorie',
    'projects.location': 'Locatie',
    'form.name': 'Naam',
    'form.email': 'E-mail',
    'form.phone': 'Telefoon',
    'form.country': 'Land',
    'form.message': 'Bericht',
    'form.comments': 'Opmerkingen',
    'form.interestLevel': 'Geschat interesseniveau (optioneel, niet-bindend)',
    'form.required': 'Verplicht',
    'form.optional': 'Optioneel',
    'form.submitRequest': 'Informatieverzoek Indienen',
    'form.sending': 'Verzenden...',
    'form.success': 'Bedankt! Uw verzoek is ontvangen. We nemen binnenkort contact met u op.',
    'form.error': 'Er is iets misgegaan. Probeer het opnieuw.',
    'form.disclaimer': 'Dit is een niet-bindende uitdrukking van interesse en vormt geen verplichting of aanbod.',
    'disclaimer.investment': 'Digital Invest Inc. is geen beleggingsadviseur, effectenmakelaar, crowdfundingplatform of openbare marktplaats. Deelname aan een project wordt privé en offline afgehandeld en alleen voor in aanmerking komende personen of entiteiten na due diligence.',
    'disclaimer.global': 'Digital Invest Inc. is een particuliere entiteit. Deze website is alleen voor informatieve doeleinden en vormt geen aanbod tot verkoop, uitnodiging tot koop of aanbeveling van effecten of financiële instrumenten.',
    'disclaimer.noGuarantees': 'Niets op deze website mag worden geïnterpreteerd als beleggings-, juridisch, fiscaal of financieel advies. Er worden geen garanties, beloftes of toekomstige rendementen gegeven of geïmpliceerd.',
    'footer.company': 'Bedrijf',
    'footer.projects': 'Projecten',
    'footer.legal': 'Juridisch & Risico',
    'footer.press': 'Pers & Bronnen',
    'footer.contact': 'Contact',
    'footer.description': 'Bouwen en opschalen van reële economie, AI, productie en gezondheidstechnologie projecten in de Verenigde Staten.',
    'footer.copyright': '© 2025 Digital Invest Inc. Alle rechten voorbehouden.',
    'team.title': 'Ons Team',
    'team.subtitle': 'Ontmoet de professionals die innovatie en groei stimuleren bij Digital Invest Inc.',
    'team.founderTitle': 'Uitvoerend Leiderschap',
    'team.teamMembers': 'Teamleden',
    'team.teamSubtitle': 'Ervaren professionals in technologie, operaties en strategische ontwikkeling',
    'glossary.title': 'Investeringswoordenlijst',
    'glossary.subtitle': 'Essentiële financiële termen en afkortingen',
    'glossary.search': 'Zoek termen...',
  },
  pl: {
    'nav.home': 'Strona Główna',
    'nav.projects': 'Projekty',
    'nav.forInvestors': 'Dla Inwestorów',
    'nav.aboutUs': 'O Nas',
    'nav.team': 'Zespół',
    'nav.contact': 'Kontakt',
    'nav.news': 'Aktualności i Analizy',
    'nav.howItWorks': 'Jak To Działa',
    'nav.investorInfo': 'Informacje dla Inwestorów',
    'common.learnMore': 'Dowiedz Się Więcej',
    'common.viewDetails': 'Zobacz Szczegóły',
    'common.viewAll': 'Zobacz Wszystko',
    'common.submit': 'Wyślij',
    'common.cancel': 'Anuluj',
    'common.save': 'Zapisz',
    'common.delete': 'Usuń',
    'common.edit': 'Edytuj',
    'common.back': 'Wstecz',
    'common.loading': 'Ładowanie...',
    'common.search': 'Szukaj',
    'common.filter': 'Filtruj',
    'common.close': 'Zamknij',
    'common.download': 'Pobierz',
    'common.readMore': 'Czytaj Więcej',
    'hero.title': 'Budowanie Projektów Realnej Gospodarki i Zaawansowanych Technologii',
    'hero.subtitle': 'Portfolio wielosektorowe obejmujące zdrowie, rolnictwo, systemy żywnościowe i infrastrukturę AI',
    'hero.cta1': 'Poznaj Projekty',
    'hero.cta2': 'Informacje Inwestycyjne',
    'projects.title': 'Nasze Projekty',
    'projects.subtitle': 'Poznaj nasze zróżnicowane portfolio projektów technologicznych i realnej gospodarki',
    'projects.featured': 'Wyróżnione Projekty',
    'projects.viewAll': 'Zobacz Wszystkie Projekty',
    'projects.status.open': 'Otwarty',
    'projects.status.closed': 'Zamknięty',
    'projects.status.comingSoon': 'Wkrótce',
    'projects.submitInterest': 'Wyrażam Zainteresowanie',
    'projects.learnMore': 'Dowiedz Się Więcej',
    'projects.category': 'Kategoria',
    'projects.location': 'Lokalizacja',
    'form.name': 'Imię',
    'form.email': 'E-mail',
    'form.phone': 'Telefon',
    'form.country': 'Kraj',
    'form.message': 'Wiadomość',
    'form.comments': 'Komentarze',
    'form.interestLevel': 'Przybliżony poziom zainteresowania (opcjonalny, niezobowiązujący)',
    'form.required': 'Wymagane',
    'form.optional': 'Opcjonalne',
    'form.submitRequest': 'Wyślij Prośbę o Informacje',
    'form.sending': 'Wysyłanie...',
    'form.success': 'Dziękujemy! Twoje zapytanie zostało otrzymane. Skontaktujemy się wkrótce.',
    'form.error': 'Coś poszło nie tak. Spróbuj ponownie.',
    'form.disclaimer': 'To jest niezobowiązujące wyrażenie zainteresowania i nie stanowi zobowiązania ani oferty.',
    'disclaimer.investment': 'Digital Invest Inc. nie jest doradcą inwestycyjnym, brokerem-dealerem, platformą crowdfundingową ani rynkiem publicznym. Udział w jakimkolwiek projekcie jest obsługiwany prywatnie, offline i tylko dla uprawnionych osób lub podmiotów po due diligence.',
    'disclaimer.global': 'Digital Invest Inc. jest prywatnym podmiotem. Ta strona internetowa służy wyłącznie celom informacyjnym i nie stanowi oferty sprzedaży, zaproszenia do zakupu ani rekomendacji papierów wartościowych lub instrumentów finansowych.',
    'disclaimer.noGuarantees': 'Nic na tej stronie nie powinno być interpretowane jako inwestycja, porada prawna, podatkowa lub finansowa. Nie są składane ani dorozumiane żadne gwarancje, obietnice ani przyszłe zwroty.',
    'footer.company': 'Firma',
    'footer.projects': 'Projekty',
    'footer.legal': 'Prawne i Ryzyko',
    'footer.press': 'Prasa i Zasoby',
    'footer.contact': 'Kontakt',
    'footer.description': 'Budowanie i skalowanie projektów realnej gospodarki, AI, produkcji i technologii zdrowotnej w Stanach Zjednoczonych.',
    'footer.copyright': '© 2025 Digital Invest Inc. Wszelkie prawa zastrzeżone.',
    'team.title': 'Nasz Zespół',
    'team.subtitle': 'Poznaj profesjonalistów napędzających innowacje i wzrost w Digital Invest Inc.',
    'team.founderTitle': 'Kierownictwo Wykonawcze',
    'team.teamMembers': 'Członkowie Zespołu',
    'team.teamSubtitle': 'Doświadczeni profesjonaliści w technologii, operacjach i rozwoju strategicznym',
    'glossary.title': 'Słownik Inwestycyjny',
    'glossary.subtitle': 'Podstawowe terminy finansowe i skróty',
    'glossary.search': 'Szukaj terminów...',
  },
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.projects': 'Projeler',
    'nav.forInvestors': 'Yatırımcılar İçin',
    'nav.aboutUs': 'Hakkımızda',
    'nav.team': 'Ekip',
    'nav.contact': 'İletişim',
    'nav.news': 'Haberler ve İçgörüler',
    'nav.howItWorks': 'Nasıl Çalışır',
    'nav.investorInfo': 'Yatırımcı Bilgileri',
    'common.learnMore': 'Daha Fazla Bilgi',
    'common.viewDetails': 'Detayları Görüntüle',
    'common.viewAll': 'Hepsini Görüntüle',
    'common.submit': 'Gönder',
    'common.cancel': 'İptal',
    'common.save': 'Kaydet',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.back': 'Geri',
    'common.loading': 'Yükleniyor...',
    'common.search': 'Ara',
    'common.filter': 'Filtrele',
    'common.close': 'Kapat',
    'common.download': 'İndir',
    'common.readMore': 'Devamını Oku',
    'hero.title': 'Gerçek Ekonomi ve İleri Teknoloji Projeleri İnşa Etmek',
    'hero.subtitle': 'Sağlık, tarım, gıda sistemleri ve yapay zeka altyapısında çok sektörlü portföy',
    'hero.cta1': 'Projeleri Keşfet',
    'hero.cta2': 'Yatırım Bilgileri',
    'projects.title': 'Projelerimiz',
    'projects.subtitle': 'Teknoloji ve gerçek ekonomi projelerinin çeşitli portföyünü keşfedin',
    'projects.featured': 'Öne Çıkan Projeler',
    'projects.viewAll': 'Tüm Projeleri Görüntüle',
    'projects.status.open': 'Açık',
    'projects.status.closed': 'Kapalı',
    'projects.status.comingSoon': 'Yakında',
    'projects.submitInterest': 'İlgi Göster',
    'projects.learnMore': 'Daha Fazla Bilgi',
    'projects.category': 'Kategori',
    'projects.location': 'Konum',
    'form.name': 'Ad',
    'form.email': 'E-posta',
    'form.phone': 'Telefon',
    'form.country': 'Ülke',
    'form.message': 'Mesaj',
    'form.comments': 'Yorumlar',
    'form.interestLevel': 'Yaklaşık ilgi seviyesi (isteğe bağlı, bağlayıcı değil)',
    'form.required': 'Gerekli',
    'form.optional': 'İsteğe Bağlı',
    'form.submitRequest': 'Bilgi Talebi Gönder',
    'form.sending': 'Gönderiliyor...',
    'form.success': 'Teşekkürler! Talebiniz alındı. Yakında sizinle iletişime geçeceğiz.',
    'form.error': 'Bir şeyler yanlış gitti. Lütfen tekrar deneyin.',
    'form.disclaimer': 'Bu bağlayıcı olmayan bir ilgi ifadesidir ve taahhüt veya teklif oluşturmaz.',
    'disclaimer.investment': 'Digital Invest Inc. bir yatırım danışmanı, broker-dealer, kitle fonlaması platformu veya halka açık pazar yeri değildir. Herhangi bir projeye katılım özel olarak, çevrimdışı ve yalnızca durum tespitinden sonra uygun bireyler veya kuruluşlar için ele alınır.',
    'disclaimer.global': 'Digital Invest Inc. özel bir kuruluştur. Bu web sitesi yalnızca bilgilendirme amaçlıdır ve satış teklifi, satın alma daveti veya menkul kıymet veya finansal araçların tavsiyesi oluşturmaz.',
    'disclaimer.noGuarantees': 'Bu web sitesindeki hiçbir şey yatırım, yasal, vergi veya finansal tavsiye olarak yorumlanmamalıdır. Herhangi bir garanti, vaat veya gelecekteki getiri yapılmamış veya ima edilmemiştir.',
    'footer.company': 'Şirket',
    'footer.projects': 'Projeler',
    'footer.legal': 'Yasal ve Risk',
    'footer.press': 'Basın ve Kaynaklar',
    'footer.contact': 'İletişim',
    'footer.description': 'Amerika Birleşik Devletleri genelinde gerçek ekonomi, yapay zeka, üretim ve sağlık teknolojisi projeleri inşa etmek ve ölçeklendirmek.',
    'footer.copyright': '© 2025 Digital Invest Inc. Tüm hakları saklıdır.',
    'team.title': 'Ekibimiz',
    'team.subtitle': 'Digital Invest Inc.\'de inovasyonu ve büyümeyi yönlendiren profesyonellerle tanışın.',
    'team.founderTitle': 'Yönetici Liderlik',
    'team.teamMembers': 'Ekip Üyeleri',
    'team.teamSubtitle': 'Teknoloji, operasyonlar ve stratejik geliştirmede deneyimli profesyoneller',
    'glossary.title': 'Yatırım Sözlüğü',
    'glossary.subtitle': 'Temel finansal terimler ve kısaltmalar',
    'glossary.search': 'Terimleri ara...',
  },
  ko: {
    'nav.home': '홈',
    'nav.projects': '프로젝트',
    'nav.forInvestors': '투자자용',
    'nav.aboutUs': '회사 소개',
    'nav.team': '팀',
    'nav.contact': '문의',
    'nav.news': '뉴스 & 인사이트',
    'nav.howItWorks': '작동 방식',
    'nav.investorInfo': '투자자 정보',
    'common.learnMore': '더 알아보기',
    'common.viewDetails': '세부 정보 보기',
    'common.viewAll': '모두 보기',
    'common.submit': '제출',
    'common.cancel': '취소',
    'common.save': '저장',
    'common.delete': '삭제',
    'common.edit': '편집',
    'common.back': '뒤로',
    'common.loading': '로딩 중...',
    'common.search': '검색',
    'common.filter': '필터',
    'common.close': '닫기',
    'common.download': '다운로드',
    'common.readMore': '더 읽기',
    'hero.title': '실물 경제 및 첨단 기술 프로젝트 구축',
    'hero.subtitle': '건강, 농업, 식품 시스템 및 AI 인프라 전반에 걸친 다중 부문 포트폴리오',
    'hero.cta1': '프로젝트 탐색',
    'hero.cta2': '투자 정보',
    'projects.title': '우리의 프로젝트',
    'projects.subtitle': '기술 및 실물 경제 프로젝트의 다양한 포트폴리오를 탐색하세요',
    'projects.featured': '주요 프로젝트',
    'projects.viewAll': '모든 프로젝트 보기',
    'projects.status.open': '열림',
    'projects.status.closed': '닫힘',
    'projects.status.comingSoon': '곧 출시',
    'projects.submitInterest': '관심 표명',
    'projects.learnMore': '더 알아보기',
    'projects.category': '카테고리',
    'projects.location': '위치',
    'form.name': '이름',
    'form.email': '이메일',
    'form.phone': '전화',
    'form.country': '국가',
    'form.message': '메시지',
    'form.comments': '의견',
    'form.interestLevel': '대략적인 관심 수준 (선택 사항, 구속력 없음)',
    'form.required': '필수',
    'form.optional': '선택 사항',
    'form.submitRequest': '정보 요청 제출',
    'form.sending': '전송 중...',
    'form.success': '감사합니다! 요청이 접수되었습니다. 곧 연락드리겠습니다.',
    'form.error': '문제가 발생했습니다. 다시 시도해 주세요.',
    'form.disclaimer': '이것은 구속력이 없는 관심 표명이며 약속이나 제안을 구성하지 않습니다.',
    'disclaimer.investment': 'Digital Invest Inc.는 투자 고문, 브로커-딜러, 크라우드펀딩 플랫폼 또는 공공 시장이 아닙니다. 모든 프로젝트 참여는 실사 후 적격 개인 또는 단체에 한해 비공개 오프라인으로 처리됩니다.',
    'disclaimer.global': 'Digital Invest Inc.는 민간 기업입니다. 이 웹사이트는 정보 제공 목적으로만 제공되며 판매 제안, 구매 권유 또는 증권이나 금융 상품의 추천을 구성하지 않습니다.',
    'disclaimer.noGuarantees': '이 웹사이트의 어떤 내용도 투자, 법률, 세금 또는 재무 조언으로 해석되어서는 안 됩니다. 어떠한 보증, 약속 또는 미래 수익도 제공되거나 암시되지 않습니다.',
    'footer.company': '회사',
    'footer.projects': '프로젝트',
    'footer.legal': '법률 및 리스크',
    'footer.press': '언론 및 리소스',
    'footer.contact': '문의',
    'footer.description': '미국 전역에서 실물 경제, AI, 제조 및 건강 기술 프로젝트를 구축하고 확장합니다.',
    'footer.copyright': '© 2025 Digital Invest Inc. 모든 권리 보유.',
    'team.title': '우리 팀',
    'team.subtitle': 'Digital Invest Inc.의 혁신과 성장을 이끄는 전문가들을 만나보세요.',
    'team.founderTitle': '경영진',
    'team.teamMembers': '팀 멤버',
    'team.teamSubtitle': '기술, 운영 및 전략적 개발 분야의 경험 많은 전문가',
    'glossary.title': '투자 용어집',
    'glossary.subtitle': '필수 금융 용어 및 약어',
    'glossary.search': '용어 검색...',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    const validLanguages: Language[] = ['en', 'ru', 'uk', 'es', 'fr', 'de', 'zh', 'ja', 'ar', 'pt', 'it', 'nl', 'pl', 'tr', 'ko'];
    return validLanguages.includes(saved) ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const langTranslations = translations[language] as Record<string, string> | undefined;
    if (!langTranslations) return key;
    return langTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
